### ISSUE TITLE
Setting value for global.imagePullSecrets creates invalid manifests

### ISSUE THREAD

**Issue by patrijua** [SigNoz/charts#163]
When setting values for global.imagePullSecrets to install signoz/signoz using Helm, rendered chart has invalid resources

```
helm install  --dry-run -n platform signoz signoz/signoz --set global.imagePullSecrets={docker-auth-config}
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ServiceAccount.metadata): unknown field "imagePullSecrets" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
```

Seems that at least the following resource is invalid as imagePullSecrets is in metadata of the object.

```
# Source: signoz/charts/clickhouse/templates/clickhouse-instance/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: signoz-clickhouse
  namespace: platform
  labels:
    helm.sh/chart: clickhouse-23.8.2
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/version: "22.8.8"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
  
  imagePullSecrets:
    - name: docker-auth-config
```
