### ISSUE TITLE
replace deprecated pod_association from K8sattribute Processor

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/charts#174]
```
k8sattributesprocessor@v0.66.0/factory.go:292	Deprecated pod_association configuration detected. Please replace:

pod_association:
- from: resource_attribute
  name: k8s.pod.ip
- from: resource_attribute
  name: k8s.pod.uid
- from: connection

with

pod_association:
- sources:
  - from: resource_attribute
    name: k8s.pod.ip
- sources:
  - from: resource_attribute
    name: k8s.pod.uid
- sources:
  - from: connection
```
