### ISSUE TITLE
k8s-infra namespace blacklisting seems incorrect

### ISSUE THREAD

**Issue by nickb937** [SigNoz/charts#193]
https://github.com/SigNoz/charts/blob/651d3f1276274e4cd17234bf235828c3738f2ec6/charts/k8s-infra/templates/_config.tpl#L216-L220

Given config like this in `values.yaml`:

```
k8s-infra:
  otelCollectorEndpoint: mon-signoz-otel-collector.platform.svc.cluster.local:4317
  presets:
    logsCollection:
      enabled: true
      blacklist:
        signozLogs: true
        namespaces:
          - platform
```

The generated section in the configmap looks like this:

```
    receivers:
      filelog/k8s:
        exclude:
        - /var/log/pods/platform_*.log
        - /var/log/pods/platform_*.log
        - /var/log/pods/*_hotrod*_*/*/*.log
        - /var/log/pods/*_locust*_*/*/*.log
        include:
        - /var/log/pods/*/*/*.log
        include_file_name: false
        include_file_path: true
        operators:
```

But I still receive logs from the platform namespace because this is the `log_file_path` recorded in clickhouse:

"/var/log/pods/platform_mon-signoz-otel-collector-dffb45dbb-r9c6r_e951d249-f208-47f3-aa35-81a096ba2ade/istio-proxy/0.log"

I would think that the path in the template is incorrect:
`- /var/log/pods/{{ $namespace }}_*.log`

Should probably be:
`- /var/log/pods/{{ $namespace }}_*/*/*.log`
