### ISSUE TITLE
Clarification needed for "logstransform/internal"

### ISSUE THREAD

**Issue by egandro** [SigNoz/charts#243]
I had a discussion with Nitya here https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1687411148945629

In his example he used

```yaml
   logstransform/parse_json:
          operators:
````

However - in your yamls for the helms it is titled `logstransform/internal` https://github.com/SigNoz/charts/blob/aef3523c392701985643c777c18651839fa5f6f4/charts/signoz/values.yaml#L1429

Something needs to be cleaned. 

- Either rename the `logstransform/internal`  to   `logstransform/parse_json`
- or add a `logstransform/custom: {}` and let the user add his or her own things.

This is not a bug - it's more a startup thing 🙈🙈🙈

**Comment by prashant-shahi** [comment]
You can use `otelCollector.config` to pass your custom configurations.
It will be merged with default values.

Example `override-values.yaml`:

```
otelCollector:
  config:
    processors:
      logstransform/custom:
        operators:
          ...
          - type: add
            id: add_database
            field: resource.database
            value: EXPR(attributes.temp.database)
            output: remove
          - id: remove
            type: remove
            field: attributes.temp
            output: noop
          # done
          - id: noop
            type: noop
    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [logstransform/internal, logstransform/custom, batch]
          exporters: [clickhouselogsexporter]
```

_Screenshot:_

![image](https://github.com/SigNoz/charts/assets/11138844/37ceb8a6-4073-46b5-8368-f9671e0b87f4)
