### ISSUE TITLE
Signoz-ingress at non-root path

### ISSUE THREAD

**Issue by bjartelund** [SigNoz/charts#280]
**Summary:**
Incorrect redirection or unexpected behavior when accessing the service via a specific path using Helm chart values.

**Description:**
I am encountering an issue with the configuration of the Helm chart values for the `signoz` service. The service is expected to be accessed via the path `/signoz/` under the hostname `example.com`. However, when attempting to access the service using the URL `example.com/signoz/`, it appears that the request is being redirected to the root path, resulting in unexpected behavior.

**Expected Behavior:**
Accessing `example.com/signoz/` should correctly route the request to the `signoz` service under the specified path.

**Actual Behavior:**
When accessing `example.com/signoz/`, the request is being redirected to the root path (`example.com/`), which is causing unintended behavior.

**Steps to Reproduce:**
1. Deploy the Helm chart with the following values configuration:
   ```yaml
   signoz:
     frontend:
       ingress:
         enabled: true
         hosts:
           - host: example.com
             paths:
               - path: /signoz/
                 pathType: Prefix
                 port: 3301
   ```
2. Access the service by entering `example.com/signoz/` in a web browser or using a tool like `curl`.

**Environment:**
- Kubernetes version: [e.g., 1.26]
- Helm version: [e.g., 3.8.2]
- Ingress Controller: [e.g., Nginx Ingress Controller, Kubernetes default]
