### ISSUE TITLE
externalClickhouse.password is required even when externalClickhouse.existingSecret is set

### ISSUE THREAD

**Issue by demeesterdev** [SigNoz/charts#318]
I have a suspicon where the password is still used but i do not know enough of the services used to know how to fix this.
see the code analysis below for my suspisions

## environment:
helm version: `version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.20.8"}`

## Steps to reproduce:
create a chart with signoz 0.29
chart.yaml excerpt:
```
apiVersion: v2
name: my-monitor
version: 1.0.0

dependencies:
# ...
- name: signoz 
  version:  "0.29.0"
  condition: signoz.enabled
  repository: "https://charts.signoz.io"
# ...
```
configure signoz values to use an external clickhouse instance:
```
# ...
signoz:
  enabled: true
  # ...
  clickhouse:
    enabled: false
  externalClickhouse:
    host: clickhouse.svc-name.svc.cluster.local
    existingSecret: my-monitoring-credentials
    existingSecretPasswordKey: my-clickhouse-password
# ... 
```

run `helm template <path to chart>`

## Expected Result:

to have this scenario work and for the key `.values.externalClickhouse.password` to be ignored.
as stated in the signoz [values.yaml]:(https://github.com/SigNoz/charts/blob/bf8f78fef1fee04715c169ea30f75290151d7e0d/charts/signoz/values.yaml#L476)
```yaml
  # -- Password for the cluster. Ignored if existingClickhouse.existingSecret is set
  password: ""
```

## Actual Result:

signoz chart returns an error stating that the password is required:
```
Error: execution error at (my-monitor/charts/signoz/templates/query-service/statefulset.yaml:16:28): externalClickhouse.password is required if using external clickhouse
helm.go:84: [debug] execution error at (my-monitor/charts/signoz/templates/query-service/statefulset.yaml:16:28): externalClickhouse.password is required if using external clickhouse
```

## Code Analysis

the value is required in the definition of
[`clickhouse.externalPasswordKey`](https://github.com/SigNoz/charts/blob/bf8f78fef1fee04715c169ea30f75290151d7e0d/charts/signoz/templates/_clickhouse.tpl#L158C5-L158C5) used in the definition of
[`clickhouse.metricsUrl`](https://github.com/SigNoz/charts/blob/bf8f78fef1fee04715c169ea30f75290151d7e0d/charts/signoz/templates/_clickhouse.tpl#L189C7-L189C7)
this metric url is used in the config map defining `prometheus.yml` in the query service [`charts/signoz/templates/query-service/configmap.yaml`](https://github.com/SigNoz/charts/blob/bf8f78fef1fee04715c169ea30f75290151d7e0d/charts/signoz/templates/query-service/configmap.yaml#L31C12-L31C12)
