### ISSUE TITLE
Clickhouse instance node selector

### ISSUE THREAD

**Issue by sarsony1** [SigNoz/charts#326]
When I set custom node selector, for clickhouse instance, they are not being passed to the chi pods that are generated. But its working fine when it comes to clickhouse operator 

Please look and it and let me know if I am missing something

Here is my config 
`clickhouse: 
    installCustomStorageClass: true
    nodeSelector:
      component: stateful
    tolerations:
      - effect: NoSchedule
        key: component
        operator: Equal
        value: stateful
    persistence:
      size: 15Gi
    resources:
      requests:
        cpu: 1000m
        memory: 1000Mi
        limits:
          cpu: 2000m
          memory: 4Gi
    settings:
      prometheus/endpoint: /metrics
      prometheus/port: 9363
      prometheus/metrics: true
      prometheus/events: true
      prometheus/asynchronous_metrics: true
    
    zookeeper:
      nodeSelector:
        component: stateful
      tolerations:
        - effect: NoSchedule
          key: component
          operator: Equal
          value: stateful

    clickhouseOperator:
      nodeSelector:
        component: stateful
      tolerations:
        - effect: NoSchedule
          key: component
          operator: Equal
          value: stateful`

**Comment by prashant-shahi** [comment]
@sarsony1 Looks like the ClickHouse Installation is not passing the node selector to the CHI pods.
Let me look into this.

Meanwhile, can you use the `affinity` and `podDistribution` (in case of multiple shards) instead?

```
clickhouse:
  affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: component
              operator: In
              values:
              - stateful
    podDistribution:
      - type: ReplicaAntiAffinity
        topologyKey: kubernetes.io/hostname
      - type: MaxNumberPerNode
        maxNumber: 1
        topologyKey: kubernetes.io/hostname
```
