### ISSUE TITLE
Error installing SigNoz when executing the Schema Migrator with external ClickHouse

### ISSUE THREAD

**Issue by n0v4c4n3** [SigNoz/charts#371]
I have a problem installing SigNoz with external ClickHouse since a change in the schema migrator Helm Chart.

When I run this comamand to install signoz 0.32.2 via helm:

helm install system-monitor signoz/signoz -f signoz-values.yaml --namespace system-monitor
with the following yaml file to override some values:
```
global:
  storageClass: gp2
  cloud: aws

clickhouse:
  enabled: false
  installCustomStorageClass: false
  size: 80Gi
  zookeeper:
    enabled: false

externalClickhouse:
  host: 172.31.12.166
  cluster: cluster
  database: signoz_metrics
  traceDatabase: signoz_traces
  user: "default"
  password: "xxx"
  existingSecret:
  existingSecretPasswordKey:
  secure: false
  verify: false
  httpPort: 8123
  tcpPort: 9000

schemaMigrator:
  enabled: true
```

I get the following error in the pod logs:
`"failed to parse dsn: parse.. port"`

This happens only **when using schema migrator** and **external ClickHouse**.
I tracked down the error and it's related to this line of code in the chart:
```
{{/*
Common ClickHouse ENV variables and helpers used by SigNoz
*/}}

{{- define "schemamigrator.dsn" }}
{{- if .Values.clickhouse.enabled -}}
{{- printf "tcp://%s:%s?username=%s&password=%s" ( include "clickhouse.servicename" . ) ( include "clickhouse.tcpPort" . ) ( .Values.clickhouse.user ) ( .Values.clickhouse.password ) -}}
{{- else -}}
{{- printf "tcp://%s:%s?username=%s&password=%s" ( required "externalClickhouse.host is required if not clickhouse.enabled" .Values.externalClickhouse.host ) ( default 9000 .Values.externalClickhouse.tcpPort ) ( .Values.externalClickhouse.user ) ( .Values.externalClickhouse.password ) -}}
{{- end }}
{{- end }}
```

Where "tcp://%s:%s?username=%s&password=%s" is handling the port with float on the dsn name and gives the error when executing the migration.

I tried an old version (0.25.4) and work perfectly.

The problem is related to this exact commit:
- https://github.com/SigNoz/charts/commit/b4e625da15a81dfd9d411941d06e59e86458f9f8

I think that changing the -dsn tcp route to handle the port in another way that doesn't prints float64 literally in the route would fix the error and fix the issue.

I would be pleased to provide any further information if it's needed.
Thanks,
regards team!
