### ISSUE TITLE
signoz-0.32.2 otel agent does not collect host metrics

### ISSUE THREAD

**Issue by lerlacher-fm** [SigNoz/charts#386]
Hello,

I've done a mostly vanilla install of signoz through helm on a self-hosted kubernetes cluster.

The signoz docs suggest that host metrics should be collected: https://signoz.io/docs/tutorial/kubernetes-infra-metrics/#list-of-metrics

However, while the k8s_* metrics are collected, I can't find any system_* metrics in signoz.

The opentelemetry docs suggest that the host rootfs needs to be mounted into the container: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/README.md#collecting-host-metrics-from-inside-a-container-linux-only

I can't see any way to pass the required config for this to the helm chart.

Is this supposed to be supported?

**Comment by srikanthccv** [comment]
You can use override-values.yaml to customize the config.

**Comment by grandwizard28** [comment]
Hi @lerlacher-fm,
We have a dedicated preset for hostmetrics as follows:
```
  hostMetrics:
    enabled: true
    collectionInterval: 30s
    scrapers:
      cpu: {}
      load: {}
      memory: {}
      disk: {}
      filesystem: {}
      network: {}
 ```
 
 This should allow to start sending hostmetrics as well!
