### ISSUE TITLE
OtelCollector and OtelCollectorMetrics Service and add custom labels

### ISSUE THREAD

**Issue by ppapp92** [SigNoz/charts#395]
We are currently trying to setup SigNoz in a multi-cluster environment that is using Linkerd as a Service Mesh. Linkerd requires a label to be set on any service that needs to be mirrored from one cluster to another.

The current values file and service templates only allow custom annotations to be passed into the OtelCollector and OtelCollectorMetrics Services. But there is no way to add custom labels.

```
  # OtelCollector service
  service:
    # -- Annotations to use by service associated to OtelCollector
    annotations: {}
    # -- Service Type: LoadBalancer (allows external access) or NodePort (more secure, no extra cost)
    type: ClusterIP
```

```
apiVersion: v1
kind: Service
metadata:
  name: {{ include "otelCollector.fullname" . }}
  labels:
    {{- include "otelCollector.labels" . | nindent 4 }}
{{- with .Values.otelCollector }}
{{- if .service.annotations }}
  annotations:
    {{- toYaml .service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .service.type }}
  ports:
    {{- include "otelCollector.portsConfig" . | indent 4 -}}
{{- end }}
  selector:
    {{- include "otelCollector.selectorLabels" . | nindent 4 }}
```
