### ISSUE TITLE
duplicate label app.kubernetes.io/component into the job schema-migrator-init

### ISSUE THREAD

**Issue by borrown** [SigNoz/charts#398]
Meanwhile installing signoz with the command  ```helm install``` it causes no problems, when trying to install via kustomize with --enable-helm parameter, the command performs an extra check that rising an error and doesn't generate the expected kubernetes schema definitions:

## How to reproduce

Create a ```kustomization.yaml``` file with next content:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: signoz
    repo: https://charts.signoz.io
    version: "0.33.2"
    releaseName: signoz
    namespace: signoz-monitoring
```

Run next command:

```bash
kustomize build <path to the directory where the previos kustomization.yaml is placed>  --enable-helm
```

## What we get

The previous command rises next error:

```
Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 10: mapping key "app.kubernetes.io/component" already defined at line 9
```

## What is expecting to get

A consistent set of kubernete schemas definitios.

## Where is located the problem

Into the file ```charts/signoz/templates/schema-migrator/migrations.yaml``` we can see how labels are generated into the Job definition from the variable ```schemaMigrator.selectorLabelsInit``` that is defined into the file ```chart/signoz/templates/_helpers.tpl``` containing one label with the key ```app.kubernetes.io/component``` . After the labels generator there is an extra hardcoded label with the next content ```app.kubernetes.io/component: init-migrations``` that is finally the key of the described error.

## Proposed solution

Removing the label ```app.kubernetes.io/component: init-migrations``` hardcoded into the file ```charts/signoz/templates/schema-migrator/migrations.yaml```
