### ISSUE TITLE
k8s-infra-otel-agent - Failed to process entry - regex parser - k3s

### ISSUE THREAD

**Issue by IzioDev** [SigNoz/charts#444]
Hi,

I've just installed Signoz on my k3s cluster, everything's fine but the 'automatic k8s metrics collection' seems to not work, by default.

```
2024-06-02T13:06:46.725Z	error	helper/transformer.go:98	Failed to process entry	{"kind": "receiver", "name": "filelog/k8s", "data_type": "logs", "operator_id": "parser-crio", "operator_type": "regex_parser", "error": {"description": "time parser: parsing time \"2024-06-02T15:06:46.70246648+02:00\" as \"2006-01-02T15:04:05.000000000-07:00\": cannot parse \".70246648+02:00\" as \".000000000\""}, "action": "send", "entry": {"observed_timestamp":"2024-06-02T13:06:46.725811448Z","timestamp":"0001-01-01T00:00:00Z","body":"2024-06-02T15:06:46.70246648+02:00 stdout F 10.42.0.1 - - [02/Jun/2024:13:06:46 +0000] \"GET / HTTP/1.1\" 200 10880 \"-\" \"kube-probe/1.28\" \"-\"","attributes":{"log":"10.42.0.1 - - [02/Jun/2024:13:06:46 +0000] \"GET / HTTP/1.1\" 200 10880 \"-\" \"kube-probe/1.28\" \"-\"","log.file.path":"/var/log/pods/signoz_signoz-frontend-86c6cd7958-pqnxb_64fd1dea-c7ec-44d1-a8f6-525551daa6be/signoz-frontend/0.log","logtag":"F","stream":"stdout","time":"2024-06-02T15:06:46.70246648+02:00"},"severity":0,"scope_name":""}}
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*TransformerOperator).HandleEntryError
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.88.0/operator/helper/transformer.go:98
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ParseWith
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.88.0/operator/helper/parser.go:175
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ProcessWithCallback
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.88.0/operator/helper/parser.go:112
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*ParserOperator).ProcessWith
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.88.0/operator/helper/parser.go:98
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/parser/regex.(*Parser).Process
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.88.0/operator/parser/regex/regex.go:99
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/transformer/router.(*Transformer).Process
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.88.0/operator/transformer/router/router.go:130
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/helper.(*WriterOperator).Write
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.88.0/operator/helper/writer.go:53
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/operator/input/file.(*Input).emit
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.88.0/operator/input/file/file.go:52
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer/internal/reader.(*Reader).ReadToEnd
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.88.0/fileconsumer/internal/reader/reader.go:106
github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza/fileconsumer.(*Manager).consume.func1
	github.com/open-telemetry/opentelemetry-collector-contrib/pkg/stanza@v0.88.0/fileconsumer/file.go:156
```

otel image: `docker.io/otel/opentelemetry-collector-contrib:0.88.0`
signoz chart version: `latest`

**Comment by ayush-rathore-quartic** [comment]
Facing the same issue when using signoz-otel-collector to **directly collect logs from the node and send to clickhouse, instead of the standard setup where k8s-infra-otel-agent does the same** (We want to combine both of these pods for Compressing SigNoz Stack as much as possible)

@nityanandagohain @IzioDev, We would any appreciate any help.

Config 

```
receivers:
  filelog/k8s:
    exclude:
    - /var/log/pods/kube-system_*/*/*.log
    - /var/log/pods/*_hotrod*_*/*/*.log
    - /var/log/pods/*_locust*_*/*/*.log
    include:
    - /var/log/pods/*/*/*.log
    include_file_name: false
    include_file_path: true
    operators:
    - id: get-format
      routes:
      - expr: body matches "^\\{"
        output: parser-docker
      - expr: body matches "^[^ Z]+ "
        output: parser-crio
      - expr: body matches "^[^ Z]+Z"
        output: parser-containerd
      type: router
    - id: parser-crio
      output: extract_metadata_from_filepath
      regex: ^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$
      timestamp:
        layout: "2006-01-02T15:04:05.000000000-07:00"
        layout_type: gotime
        parse_from: attributes.time
      type: regex_parser
    - id: parser-containerd
      output: extract_metadata_from_filepath
      regex: ^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$
      timestamp:
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        parse_from: attributes.time
      type: regex_parser
    - id: parser-docker
      output: extract_metadata_from_filepath
      timestamp:
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
        parse_from: attributes.time
      type: json_parser
    - id: extract_metadata_from_filepath
      output: add_cluster_name
      parse_from: attributes["log.file.path"]
      regex: ^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]+)\/(?P<container_name>[^\._]+)\/(?P<restart_count>\d+)\.log$
      type: regex_parser
    - field: resource["k8s.cluster.name"]
      id: add_cluster_name
      output: move_stream
      type: add
      value: EXPR(env("K8S_CLUSTER_NAME"))
    - from: attributes.stream
      id: move_stream
      output: move_container_name
      to: attributes["log.iostream"]
      type: move
    - from: attributes.container_name
      id: move_container_name
      output: move_namespace
      to: resource["k8s.container.name"]
      type: move
    - from: attributes.namespace
      id: move_namespace
      output: move_pod_name
      to: resource["k8s.namespace.name"]
      type: move
    - from: attributes.pod_name
      id: move_pod_name
      output: move_restart_count
      to: resource["k8s.pod.name"]
      type: move
    - from: attributes.restart_count
      id: move_restart_count
      output: move_uid
      to: resource["k8s.container.restart_count"]
      type: move
    - from: attributes.uid
      id: move_uid
      output: move_log
      to: resource["k8s.pod.uid"]
      type: move
    - from: attributes.log
      id: move_log
      to: body
      type: move
    start_at: beginning
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 16
      http:
        endpoint: 0.0.0.0:4318
```
```
processors:
  batch:
    send_batch_size: 30000
    timeout: 5s
  k8sattributes:
    extract:
      metadata:
      - k8s.namespace.name
      - k8s.pod.name
      - k8s.pod.uid
      - k8s.pod.start_time
      - k8s.deployment.name
      - k8s.node.name
    filter:
      node_from_env_var: K8S_NODE_NAME
    passthrough: false
    pod_association:
    - sources:
      - from: resource_attribute
        name: k8s.pod.ip
    - sources:
      - from: resource_attribute
        name: k8s.pod.uid
    - sources:
      - from: connection

```
```
exporters:
  clickhouselogsexporter:
    dsn: tcp://${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}@${CLICKHOUSE_HOST}:${CLICKHOUSE_PORT}/${CLICKHOUSE_LOG_DATABASE}
    timeout: 60s
```


```
  pipelines:
    logs:
      exporters:
      - clickhouselogsexporter
      processors:
      - batch
      - k8sattributes
      receivers:
      - otlp
      - filelog/k8s
```


Error Logs:

`2024-07-23T21:09:32.715Z	error	helper/transformer.go:98	Failed to process entry	{"kind": "receiver", "name": "filelog/k8s", "data_type": "logs", "operator_id": "parser-containerd", "operator_type": "regex_parser", "error": {"description": "time parser: parsing time \"-23T15:40:11.234421148Z\" as \"2006-01-02T15:04:05.999Z\": cannot parse \"-23T15:40:11.234421148Z\" as \"2006\""}, "action": "send", "entry": {"observed_timestamp":"2024-07-23T21:09:32.71552963Z","timestamp":"0001-01-01T00:00:00Z","body":"-23T15:40:11.234421148Z stdout F time=\"2024-07-23T15:40:11Z\" level=info msg=\"Updating ingress [default:strimzi-cluster-kafka-external-0] with public endpoints [[{\\\"addresses\\\":[\\\"10.12.0.7\\\"],\\\"port\\\":443,\\\"protocol\\\":\\\"HTTPS\\\",\\\"serviceName\\\":\\\"default:strimzi-cluster-kafka-external-0\\\",\\\"ingressName\\\":\\\"default:strimzi-cluster-kafka-external-0\\\",\\\"hostname\\\":\\\"qa-zero.quartickafka.in\\\",\\\"path\\\":\\\"/\\\",\\\"allNodes\\\":false}]]\"","attributes":{"log":"time=\"2024-07-23T15:40:11Z\" level=info msg=\"Updating ingress [default:strimzi-cluster-kafka-external-0] with public endpoints [[{\\\"addresses\\\":[\\\"10.12.0.7\\\"],\\\"port\\\":443,\\\"protocol\\\":\\\"HTTPS\\\",\\\"serviceName\\\":\\\"default:strimzi-cluster-kafka-external-0\\\",\\\"ingressName\\\":\\\"default:strimzi-cluster-kafka-external-0\\\",\\\"hostname\\\":\\\"qa-zero.quartickafka.in\\\",\\\"path\\\":\\\"/\\\",\\\"allNodes\\\":false}]]\"","log.file.path":"/var/log/pods/cattle-system_cattle-cluster-agent-65f87fcc86-vbfhj_fcd9bd22-0058-4b2b-aeac-72291640d900/cluster-register/0.log","logtag":"F","stream":"stdout","time":"-23T15:40:11.234421148Z"},"severity":0,"scope_name":""}}`
