### ISSUE TITLE
Kubernetes events configuration missing in Signoz K8S Infra Helm chart

### ISSUE THREAD

**Issue by IvaskevychYuriy** [SigNoz/charts#497]
# Description
Hello, I've installed `signoz` and `k8s-infra` helm charts on my local cluster and I can see all the logs and host metrics etc.
But I cannot figure out how to configure kubernetes events to be logged into Signoz as well using existing OTEL collector configurations - helm chart values don't seem to have such an option.
Not sure if the setup is helpful but I'm sharing it below.

# Setup
1. Add repo: `helm repo add signoz https://charts.signoz.io`
2. Install `signoz` chart: `helm upgrade -i -f ./signoz.yaml --version 0.50.0 signoz signoz/signoz`
Values override `./signoz.yaml`:
   ```yaml
   alertmanager:
     enabled: false
   clickhouse:
     zookeeper:
       enabled: true
     persistence:
       size: 10Gi
   otelCollectorMetrics:
     enabled: true
   ```
3. Install `k8s-infra` helm chart: `helm upgrade -i -f ./signoz-k8s.yaml --version 0.11.10 signoz-k8s signoz/k8s-infra`
Values override `/signoz-k8s.yaml`:
   ```yaml
   enabled: true
   otelCollectorEndpoint: signoz-otel-collector:4317
   otelAgent:
     enabled: true
   otelDeployment:
     enabled: true
   ```

# Issue
I see that `k8s-infra` chart defines [`presets` values](https://github.com/SigNoz/charts/blob/0b4abd1e007bcc68d1335395b66ca667e05a1e1b/charts/k8s-infra/values.yaml#L82) to configure the OTEL service and the defaults look good **_except_** I don't see a setting to collect Kubernetes events.

For contrast if one checks OTEL collector helm chart (current version `0.104.0`) - it does expose [such setting in `preset`](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/283cc1ae2d70bc0cb9b3851081cf69a96ffd673f/charts/opentelemetry-collector/values.yaml#L70) to configure events collection. 
![image](https://github.com/user-attachments/assets/55c088d8-f75f-4977-88e1-178644c30c10)

A workaround would be to setup yet another OTEL collector in the cluster using OTEL helm charts to collect K8S events and push them to Signoz OTEL collector endpoint.

But I believe it should be configurable directly in `k8s-infra` helm chart preset.

# Versions
- k8s distro: K3S
- kubectl: 1.30.2 (client), 1.29.6+k3s2 (server)
- helm: 3.15.1
- `signoz` helm chart: 0.50.0
- `k8s-infra` helm chart: 0.11.10
