### ISSUE TITLE
[BUG] Impossible to upgrade Chart to the latest version before create ServiceAccount, Role, RoleBinding, for sync and async

### ISSUE THREAD

**Issue by TheDevilDan** [SigNoz/charts#543]
Impossible to upgrade helm chart because charts need ressources for jobs, I have to create manually to workaround :

```
upgrade.go:487: 2024-10-29 15:26:47.480194328 +0100 CET m=+320.096239113 [debug] warning: Upgrade "release-demo" failed: pre-upgrade hooks failed: 1 error occurred:
        * timed out waiting for the condition


Error: UPGRADE FAILED: pre-upgrade hooks failed: 1 error occurred:
        * timed out waiting for the condition


helm.go:86: 2024-10-29 15:26:47.634100017 +0100 CET m=+320.250144852 [debug] pre-upgrade hooks failed: 1 error occurred:
        * timed out waiting for the condition


UPGRADE FAILED
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:243
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:85
runtime.main
        runtime/proc.go:271
runtime.goexit
        runtime/asm_amd64.s:1695
```
First error in job : 
```
Error creating: pods "release-demo-signoz-schema-migrator-sync-" is forbidden: error looking up service account platform/release-demo-signoz-schema-migrator-sync: serviceaccount "release-demo-signoz-schema-migrator-sync" not found
```
If I create serviceaccount :
```
Error from server (Forbidden): jobs.batch "release-demo-signoz-schema-migrator-sync" is forbidden: User "system:serviceaccount:platform:release-demo-signoz-schema-migrator-async" cannot get resource "jobs" in API group "batch" in the namespace "platform"
```
If I create all ressources, the upgrade can be done : Fix to apply before upgrade from 0.55 to 0.56, don't forget to add/modify Annotations + Labels :
```
---
# Source: signoz/templates/schema-migrator/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: release-demo
    meta.helm.sh/release-namespace: platform
  name: release-demo-signoz-schema-migrator-sync
  labels:
    helm.sh/chart: signoz-0.55.0
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: release-demo
    app.kubernetes.io/version: "0.57.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: signoz/templates/schema-migrator-async/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: release-demo
    meta.helm.sh/release-namespace: platform
  name: release-demo-signoz-schema-migrator-async
  labels:
    helm.sh/chart: signoz-0.55.0
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: release-demo
    app.kubernetes.io/version: "0.57.0"
    app.kubernetes.io/managed-by: Helm

---
# Source: signoz/templates/schema-migrator-async/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: release-demo
    meta.helm.sh/release-namespace: platform
  name: release-demo-signoz-schema-migrator-platform-async
  namespace: platform
  labels:
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
    - batch
    resources:
    - jobs
    verbs:
    - get
    - list
    - watch
---
# Source: signoz/templates/schema-migrator/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: release-demo
    meta.helm.sh/release-namespace: platform
  name: release-demo-signoz-schema-migrator-platform-sync
  namespace: platform
  labels:
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
    - batch
    resources:
    - jobs
    verbs:
    - get
    - list
    - watch
---
# Source: signoz/templates/schema-migrator-async/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: release-demo
    meta.helm.sh/release-namespace: platform
  labels:
    app.kubernetes.io/managed-by: Helm
  name: release-demo-signoz-schema-migrator-platform-async
  namespace: platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-demo-signoz-schema-migrator-platform-async
subjects:
  - name: release-demo-signoz-schema-migrator-async
    kind: ServiceAccount
    namespace: platform
---
# Source: signoz/templates/schema-migrator/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: release-demo
    meta.helm.sh/release-namespace: platform
  labels:
    app.kubernetes.io/managed-by: Helm
  name: release-demo-signoz-schema-migrator-platform-sync
  namespace: platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-demo-signoz-schema-migrator-platform-sync
subjects:
  - name: release-demo-signoz-schema-migrator-sync
    kind: ServiceAccount
    namespace: platform
```
