### ISSUE TITLE
Enable all kinds of env variables in query-service

### ISSUE THREAD

**Issue by grandwizard28** [SigNoz/charts#578]
## Description

Users may wish to configure `env` of `query-service` in multiple ways. Instead of treating each requirement separately, we should provide a configuration like the following:

```
additionalEnvs:
  env_from_secret:
    valueFrom:
      secretKeyRef:
        key: secret-1
        name: key-1
  env_from_configmap:
    valueFrom:
       configMapKeyRef:
          name: configmap-1
          key: key-1
   env_value: custom-value
```

This will give users the flexibility to manage env variables as they wish.
