### ISSUE TITLE
Error installing signoz on KubeSphere with signoz chart

### ISSUE THREAD

**Issue by GouShengZ** [SigNoz/charts#584]
coalesce.go:163: warning: skipped value for initContainers: Not a table. Error: parse error at (signoz/templates/query-service/statefulset.yaml:148): unclosed action

**Comment by grandwizard28** [comment]
Hi @GouShengZ,
Can you provide the following details:

- The `values.yaml` file used
- Version of charts being used

**Comment by danbopes** [comment]
Got something similar:
```
coalesce.go:237: warning: skipped value for zookeeper.initContainers: Not a table.
```
My values:

```
clickhouse:
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    size: 40Gi
frontend:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-realm: Authentication Required
      nginx.ingress.kubernetes.io/auth-secret: mt-auth
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/backend-protocol: GRPC
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    enabled: true
    hosts:
    - host: signoz.k8s.mydomain.com
      paths:
      - path: /
        pathType: ImplementationSpecific
        port: 4318
    tls:
    - hosts:
      - signoz.k8s.mydomain.com
      secretName: signoz-frontend-tls
otelCollector:
  ingress:
    annotations: {}
    enabled: true
    hosts:
    - host: ingest.k8s.mydomain.com
      paths:
      - path: /
        pathType: ImplementationSpecific
        port: 4318
    tls:
    - hosts:
      - ingest.k8s.mydomain.com
      secretName: ingest-tls
```
