### ISSUE TITLE
Incorrect volume mounts for clickhouse

### ISSUE THREAD

**Issue by yukimotochern** [SigNoz/charts#594]
When using existing pvc for clickhouse, the below code are wrong.
`charts/clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml`

```yaml
              {{- if and (.Values.persistence.enabled) (.Values.persistence.existingClaim) }}
                - name: existing-volumeclaim
                  mountPath: /var/lib/clickhouse
               {{- end }}
              {{- if .Values.persistence.enabled }}
                - name: data-volumeclaim-template
                  mountPath: /var/lib/clickhouse
              {{- end }}
```
This causes duplicate volume mount paths.
