### ISSUE TITLE
Error installing 0.70.0:

### ISSUE THREAD

**Issue by softlion** [SigNoz/charts#622]
```history.go:56: 2025-02-17 11:53:41.6645701 +0100 CET m=+0.370978001 [debug] getting history for release signoz
Release "signoz" does not exist. Installing it now.
install.go:225: 2025-02-17 11:53:41.7048573 +0100 CET m=+0.411265201 [debug] Original chart version: ""
install.go:242: 2025-02-17 11:53:42.9384067 +0100 CET m=+1.644814601 [debug] CHART PATH: C:\Users\BENJA_~1\AppData\Local\Temp\helm\repository\signoz-0.70.0.tgz

coalesce.go:237: warning: skipped value for zookeeper.initContainers: Not a table.
install.go:263: 2025-02-17 11:53:43.0164758 +0100 CET m=+1.722883701 [debug] WARNING: This chart or one of its subcharts contains CRDs. Rendering may fail or contain inaccuracies.
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "signoz-clickhouse" namespace: "signoz" from "": no matches for kind "ClickHouseInstallation" in version "clickhouse.altinity.com/v1"
ensure CRDs are installed first
helm.go:86: 2025-02-17 11:53:44.478965 +0100 CET m=+3.185372901 [debug] resource mapping not found for name: "signoz-clickhouse" namespace: "signoz" from "": no matches for kind "ClickHouseInstallation" in version "clickhouse.altinity.com/v1"
ensure CRDs are installed first
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
        helm.sh/helm/v3/pkg/action/install.go:334
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:317
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:160
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.1/command.go:985
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.1/command.go:1117
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.1/command.go:1041
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:85
runtime.main
        runtime/proc.go:272
runtime.goexit
        runtime/asm_amd64.s:1700

**Comment by softlion** [comment]
values file:

```
clickhouse:
  persistence:
    existingClaim: signoz-clickhouse



queryService:
  persistence:
    existingClaim: signoz-query
  
  
frontend:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: my.domain.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: signoz
        hosts:
          - my.domain.com
  
  
  
alertmanager:
  persistence:
    existingClaim: signoz-alertmanager
  ingress:
    enabled: false



otelCollector:
  service:
    type: ClusterIP
  ingress:
    enabled: false



otelCollectorMetrics:
  ingress:
    enabled: false



signoz-otel-gateway:
  enabled: false
```
