### ISSUE TITLE
Simple install fails: create_directories: Permission denied

### ISSUE THREAD

**Issue by softlion** [SigNoz/charts#623]
```
std::exception. Code: 1001, type: std::__1::__fs::filesystem::filesystem_error, e.what() = filesystem error: in create_directories: Permission denied ["/var/lib/clickhouse/preprocessed_configs"], Stack trace (when copying this message, always include the lines below):

0. std::system_error::system_error(std::error_code, String const&) @ 0x000000001717d955 in /usr/bin/clickhouse
1. std::__fs::filesystem::filesystem_error::filesystem_error[abi:v15000](String const&, std::__fs::filesystem::path const&, std::error_code) @ 0x000000000c84d381 in /usr/bin/clickhouse
2. void std::__fs::filesystem::__throw_filesystem_error[abi:v15000]<String&, std::__fs::filesystem::path const&, std::error_code const&>(String&, std::__fs::filesystem::path const&, std::error_code const&) @ 0x000000001713445a in /usr/bin/clickhouse
3. std::__fs::filesystem::detail::(anonymous namespace)::ErrorHandler<bool>::report(std::error_code const&) const (.llvm.6363049823438148879) @ 0x00000000171377b6 in /usr/bin/clickhouse
4. std::__fs::filesystem::__create_directories(std::__fs::filesystem::path const&, std::error_code*) @ 0x0000000017137fb9 in /usr/bin/clickhouse
5. DB::ConfigProcessor::savePreprocessedConfig(DB::ConfigProcessor::LoadedConfig&, String) @ 0x0000000012fe567e in /usr/bin/clickhouse
6. BaseDaemon::initialize(Poco::Util::Application&) @ 0x000000000cae53dc in /usr/bin/clickhouse
7. DB::Server::initialize(Poco::Util::Application&) @ 0x000000000c88fc18 in /usr/bin/clickhouse
8. Poco::Util::Application::run() @ 0x00000000153b26ba in /usr/bin/clickhouse
9. DB::Server::run() @ 0x000000000c88f9d1 in /usr/bin/clickhouse
10. Poco::Util::ServerApplication::run(int, char**) @ 0x00000000153bb539 in /usr/bin/clickhouse
11. mainEntryClickHouseServer(int, char**) @ 0x000000000c88c8ca in /usr/bin/clickhouse
12. main @ 0x0000000007216ad8 in /usr/bin/clickhouse
13. ? @ 0x00007f989151c083
14. _start @ 0x0000000005f6f12e in /usr/bin/clickhouse
```

**Comment by softlion** [comment]
```
k version
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.32.1
```

**Comment by softlion** [comment]
```
k get storageclass
NAME             PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
slow (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   true                   2y85d
```

**Comment by softlion** [comment]
Ok the problem is, `volumePermissions` must be enabled in the bitnami charts.

I was able to enable the one for zookeeper, but not the one for clickhouse:  
It looks like you need to fix your chart.

```yaml
clickhouse:
  persistence:
    existingClaim: signoz-clickhouse
  volumePermissions:
    enabled: true
  zookeeper:
    persistence:
      existingClaim: signoz-zookeeper
    volumePermissions:
      enabled: true
```

**Comment by softlion** [comment]
I was able to get it working by manually editing the statefulset :

```bash
k edit statefulset chi-signoz-clickhouse-cluster-0-0 -n signoz
```

The add this to the initContainers section;
```yaml
      initContainers:
      - args:
        - chown -R 101:101 /var/lib/clickhouse
        command:
        - /bin/sh
        - -c
        image: bitnami/minideb
        imagePullPolicy: Always
        name: volume-permissions
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/clickhouse
          name: existing-volumeclaim
```
