### ISSUE TITLE
Configure Ingress for both HTTP and GRPC otelCollector

### ISSUE THREAD

**Issue by c5racing** [SigNoz/charts#639]
This doc is great for getting self hosted running behind NGINX: https://signoz.io/docs/tutorial/setting-up-tls-for-signoz. It works out of the box for GRPC and the web front end. Unfortunately, the HTTP collector doesn't receive ingress traffic.

Can I get some assistance in setting up the ingress traffic for the HTTP collector?

If I configure my values.yaml file as the following, my GRPC quits working:

`  ingress: enabled: true className: nginx hosts: - host: signoz-ingest.example.com paths: - path: /v1/traces pathType: ImplementationSpecific port: 4318  # HTTP ingestion - path: /v1/metrics pathType: ImplementationSpecific port: 4318  # HTTP ingestion - path: /v1/logs pathType: ImplementationSpecific port: 4318  # HTTP ingestion - path: / pathType: ImplementationSpecific port: 4317  # GRPC ingestion tls: - secretName: signoz-ingest-tls-cert hosts: - signoz-ingest.example.com annotations: cert-manager.io/cluster-issuer: letsencrypt-production nginx.ingress.kubernetes.io/ssl-redirect: "true"`

If I add back in nginx.ingress.kubernetes.io/backend-protocol: "GRPC" under annotataions, then my HTTP quits working

**Comment by grandwizard28** [comment]
Yeah,
The implementation idea is simple. We need to create 2 ingresses: One for grpc, one for http:

### Spec for `ingress/signoz-otel-collector-grpc`:

```
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
spec:
  ingressClassName: nginx
  rules:
  - host: <host>
    http:
      paths:
      - backend:
          service:
            name: signoz-otel-collector
            port:
              number: 4317
        path: /opentelemetry.proto.collector.logs.v1.LogsService/Export
        pathType: Exact
      - backend:
          service:
            name: signoz-otel-collector
            port:
              number: 4317
        path: /opentelemetry.proto.collector.metrics.v1.MetricsService/Export
        pathType: Exact
      - backend:
          service:
            name: signoz-otel-collector
            port:
              number: 4317
        path: /opentelemetry.proto.collector.trace.v1.TraceService/Export
        pathType: Exact
```

### Spec for `ingress/signoz-otel-collector-http`:

```
spec:
  ingressClassName: nginx
  rules:
  - host: <host>
    http:
      paths:
      - backend:
          service:
            name:  signoz-otel-collector
            port:
              number: 4318
        path: /v1/logs
        pathType: Exact
      - backend:
          service:
            name:  signoz-otel-collector
            port:
              number: 4318
        path: /v1/metrics
        pathType: Exact
      - backend:
          service:
            name:  signoz-otel-collector
            port:
              number: 4318
        path: /v1/traces
        pathType: Exact
```
