### ISSUE TITLE
"Failed to create signoz struct" when deploying the helm chart

### ISSUE THREAD

**Issue by wertzui** [SigNoz/charts#640]
I just tried to deploy the signoz/signoz helm chart in our on prem Kubernetes.

I used the following values.yaml
```yaml
global:
  storageClass: nfs-client

clickhouse:
  installCustomStorageClass: true

signoz:
  ingress:
    # -- Enable ingress for signoz
    enabled: true
    # -- Ingress Class Name to be used to identify ingress controllers
    className: ""
    # -- Annotations to signoz Ingress
    annotations:
      kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    # -- signoz Ingress Host names with their path details
    hosts:
      - host: signoz.removed.com
        paths:
          - path: /
            pathType: ImplementationSpecific
            port: 8080
    # -- signoz Ingress TLS
    tls:
      - secretName: star-removed-com
        hosts:
          - signoz.removed.com

otelCollector:
  ingress:
    # -- Enable ingress for OtelCollector
    enabled: true
    # -- Ingress Class Name to be used to identify ingress controllers
    className: ""
    # -- Annotations to OtelCollector Ingress
    annotations:
      kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    # -- OtelCollector Ingress Host names with their path details
    hosts:
      - host: otelcollector.removed.com
        paths:
          - path: /
            pathType: ImplementationSpecific
            port: 4318
    # -- OtelCollector Ingress TLS
    tls:
      - secretName: star-removed-com
        hosts:
          - otelcollector.removed.com

```

However the starting Signoz pod always returns an error while starting up
```log
SigNoz version   : v0.76.2
Commit SHA-1     : 031e78c
Commit timestamp : 2025-03-18T09:18:20Z
Branch           : HEAD
Go version       : go1.22.12

For SigNoz Official Documentation,  visit https://signoz.io/docs/
For SigNoz Community Slack,         visit http://signoz.io/slack/
For archive of discussions about SigNoz,       visit https://knowledgebase.signoz.io/

Check SigNoz Github repo for license details.
Copyright 2024 SigNoz

[Deprecated] env STORAGE is deprecated and scheduled for removal. Please use SIGNOZ_TELEMETRYSTORE_PROVIDER instead.
[Deprecated] env ClickHouseUrl is deprecated and scheduled for removal. Please use SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN instead.
{"timestamp":"2025-03-25T07:31:18.784638214Z","level":"INFO","code":{"function":"go.signoz.io/signoz/pkg/sqlstore/sqlitesqlstore.New","file":"/home/runner/work/signoz/signoz/pkg/sqlstore/sqlitesqlstore/provider.go","line":45},"msg":"connected to sqlite","logger":"go.signoz.io/signoz/pkg/sqlitesqlstore","path":"/var/lib/signoz/signoz.db"}
{"timestamp":"2025-03-25T07:31:18.785463747Z","level":"INFO","code":{"function":"go.signoz.io/signoz/pkg/sqlmigrator.(*migrator).Migrate","file":"/home/runner/work/signoz/signoz/pkg/sqlmigrator/migrator.go","line":43},"msg":"starting sqlstore migrations","logger":"go.signoz.io/signoz/pkg/sqlmigrator","dialect":"sqlite"}
{"level":"FATAL","timestamp":"2025-03-25T07:31:18.826Z","caller":"query-service/main.go:161","msg":"Failed to create signoz struct","error":"disk I/O error: input/output error","stacktrace":"main.main\n\t/home/runner/work/signoz/signoz/ee/query-service/main.go:161\nruntime.main\n\t/opt/hostedtoolcache/go/1.22.12/x64/src/runtime/proc.go:271"}
```

I checked the nfs share which is the underlying storage for the PVC and I can see folders being created for Zookeper, Clickhouse and Signoz.

Is there anything, I'm missing?
