### ISSUE TITLE
K8s-infra chart does not apply deployenv for Prometheus scraper

### ISSUE THREAD

**Issue by Soortor** [SigNoz/charts#647]
Hello,

We are using the newly added feature to K8S-infra for scraping pods that use Prometheus metrics.
Unfortunately, it seems like the resulting configMap does not have a processor which adds the deploymentEnvironment for the exported scraper metrics.
This makes it impossible to filter by environment in Signoz. Is this intentional, or an oversight?

Chart values:
```
k8s-infra:
  global:
    clusterName: redacted
    deploymentEnvironment: staging <--
    cloud: azure
  clusterName: redacted
  otelCollectorEndpoint: redacted
 ...
  presets:
    prometheus:
      enabled: true
      annotationsPrefix: prometheus.io
      includePodLabel: true
```

Generated config map:
```

service:
  extensions:
  - health_check
  - zpages
  - pprof
  pipelines:
    logs:
      exporters:
      - otlp
      processors:
      - resource/deployenv
      - resourcedetection
      - batch
      receivers:
      - k8s_events
    metrics/internal:
      exporters:
      - otlp
      processors:
      - resource/deployenv
      - resourcedetection
      - batch
      receivers:
      - k8s_cluster
    metrics/scraper:
      exporters:
      - otlp
      processors:
      - resourcedetection
      - batch
      - resource/deployenv <-- this is missing
      receivers:
      - prometheus/scraper
```
