### ISSUE TITLE
[Bug][k8s-infra] failed to read usage at `/hostfs/conf`: no such file or directory

### ISSUE THREAD

**Issue by ToshY** [SigNoz/charts#665]
**Problem**

Looking at logs of the otel-agent it shows errors in all pods that are deployed:

```text
failed to read usage at /hostfs/conf: no such file or directory; 
failed to read usage at /hostfs/hostfs: no such file or directory; 
failed to read usage at /hostfs/hostfs/var: no such file or directory; 
failed to read usage at /hostfs/hostfs/root: no such file or directory; 
failed to read usage at /hostfs/hostfs/.snapshots: no such file or directory; 
failed to read usage at /hostfs/hostfs/boot/grub2/i386-pc: no such file or directory; 
failed to read usage at /hostfs/hostfs/boot/writable: no such file or directory; 
failed to read usage at /hostfs/hostfs/boot/grub2/x86_64-efi: no such file or directory;
failed to read usage at /hostfs/hostfs/opt: no such file or directory; 
failed to read usage at /hostfs/hostfs/home: no such file or directory; 
failed to read usage at /hostfs/hostfs/boot/efi: no such file or directory; 
failed to read usage at /hostfs/hostfs/srv: no such file or directory;
failed to read usage at /hostfs/hostfs/usr/local: no such file or directory
```

Think `/hostfs/hostfs` is wrong.

**Config**

`values.yaml`
```yaml
global:
  cloud: other
  clusterName: ${CLUSTER_NAME}
  deploymentEnvironment: ${CLUSTER_DEPLOYMENT_ENVIRONMENT}

otelCollectorEndpoint: ${HELM_K8S_INFRA_RELEASE_NAME}-otel-agent.${HELM_K8S_INFRA_NAMESPACE}.svc:4317
otelInsecure: true

presets:
  loggingExporter:
    enabled: false
  otlpExporter:
    enabled: true
  hostMetrics:
    enabled: true
    collectionInterval: 60s
  kubeletMetrics:
    enabled: true
  prometheus:
    enabled: false
  resourceDetection:
    enabled: true
    timeout: 2s
    override: false
  k8sEvents:
    enabled: true
```

**Traces**

```json
[
  {
    "level": "error",
    "ts": 1747252138.267195,
    "caller": "scraperhelper/scrapercontroller.go:197",
    "msg": "Error scraping metrics",
    "kind": "receiver",
    "name": "hostmetrics",
    "data_type": "metrics",
    "error": "failed to read usage at /hostfs/conf: no such file or directory; failed to read usage at /hostfs/hostfs: no such file or directory; failed to read usage at /hostfs/hostfs/root: no such file or directory; failed to read usage at /hostfs/hostfs/var: no such file or directory; failed to read usage at /hostfs/hostfs/.snapshots: no such file or directory; failed to read usage at /hostfs/hostfs/boot/grub2/i386-pc: no such file or directory; failed to read usage at /hostfs/hostfs/boot/grub2/x86_64-efi: no such file or directory; failed to read usage at /hostfs/hostfs/home: no such file or directory; failed to read usage at /hostfs/hostfs/boot/writable: no such file or directory; failed to read usage at /hostfs/hostfs/opt: no such file or directory; failed to read usage at /hostfs/hostfs/srv: no such file or directory; failed to read usage at /hostfs/hostfs/usr/local: no such file or directory; failed to read usage at /hostfs/hostfs/boot/efi: no such file or directory",
    "scraper": "hostmetrics",
    "stacktrace": "go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport\n\tgo.opentelemetry.io/collector/receiver@v0.109.0/scraperhelper/scrapercontroller.go:197\ngo.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1\n\tgo.opentelemetry.io/collector/receiver@v0.109.0/scraperhelper/scrapercontroller.go:173"
  },
  {
    "level": "error",
    "ts": 1747252139.5428674,
    "caller": "exporterhelper/queue_sender.go:92",
    "msg": "Exporting failed. Dropping data.",
    "kind": "exporter",
    "data_type": "metrics",
    "name": "otlp",
    "error": "not retryable error: Permanent error: rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (4194305 vs. 4194304)",
    "dropped_items": 14339,
    "stacktrace": "go.opentelemetry.io/collector/exporter/exporterhelper.newQueueSender.func1\n\tgo.opentelemetry.io/collector/exporter@v0.109.0/exporterhelper/queue_sender.go:92\ngo.opentelemetry.io/collector/exporter/internal/queue.(*boundedMemoryQueue[...]).Consume\n\tgo.opentelemetry.io/collector/exporter@v0.109.0/internal/queue/bounded_memory_queue.go:52\ngo.opentelemetry.io/collector/exporter/internal/queue.(*Consumers[...]).Start.func1\n\tgo.opentelemetry.io/collector/exporter@v0.109.0/internal/queue/consumers.go:43"
  },
  {
    "level": "error",
    "ts": 1747252156.867089,
    "caller": "scraperhelper/scrapercontroller.go:197",
    "msg": "Error scraping metrics",
    "kind": "receiver",
    "name": "hostmetrics",
    "data_type": "metrics",
    "error": "failed to read usage at /hostfs/conf: no such file or directory; failed to read usage at /hostfs/hostfs: no such file or directory; failed to read usage at /hostfs/hostfs/var: no such file or directory; failed to read usage at /hostfs/hostfs/root: no such file or directory; failed to read usage at /hostfs/hostfs/.snapshots: no such file or directory; failed to read usage at /hostfs/hostfs/boot/grub2/i386-pc: no such file or directory; failed to read usage at /hostfs/hostfs/boot/writable: no such file or directory; failed to read usage at /hostfs/hostfs/boot/grub2/x86_64-efi: no such file or directory; failed to read usage at /hostfs/hostfs/opt: no such file or directory; failed to read usage at /hostfs/hostfs/home: no such file or directory; failed to read usage at /hostfs/hostfs/boot/efi: no such file or directory; failed to read usage at /hostfs/hostfs/srv: no such file or directory; failed to read usage at /hostfs/hostfs/usr/local: no such file or directory",
    "scraper": "hostmetrics",
    "stacktrace": "go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport\n\tgo.opentelemetry.io/collector/receiver@v0.109.0/scraperhelper/scrapercontroller.go:197\ngo.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1\n\tgo.opentelemetry.io/collector/receiver@v0.109.0/scraperhelper/scrapercontroller.go:173"
  },
  {
    "level": "error",
    "ts": 1747252158.3260977,
    "caller": "scraperhelper/scrapercontroller.go:197",
    "msg": "Error scraping metrics",
    "kind": "receiver",
    "name": "hostmetrics",
    "data_type": "metrics",
    "error": "failed to read usage at /hostfs/conf: no such file or directory; failed to read usage at /hostfs/hostfs: no such file or directory; failed to read usage at /hostfs/hostfs/var: no such file or directory; failed to read usage at /hostfs/hostfs/root: no such file or directory; failed to read usage at /hostfs/hostfs/.snapshots: no such file or directory; failed to read usage at /hostfs/hostfs/boot/grub2/i386-pc: no such file or directory; failed to read usage at /hostfs/hostfs/boot/grub2/x86_64-efi: no such file or directory; failed to read usage at /hostfs/hostfs/boot/writable: no such file or directory; failed to read usage at /hostfs/hostfs/home: no such file or directory; failed to read usage at /hostfs/hostfs/srv: no such file or directory; failed to read usage at /hostfs/hostfs/opt: no such file or directory; failed to read usage at /hostfs/hostfs/usr/local: no such file or directory; failed to read usage at /hostfs/hostfs/boot/efi: no such file or directory",
    "scraper": "hostmetrics",
    "stacktrace": "go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport\n\tgo.opentelemetry.io/collector/receiver@v0.109.0/scraperhelper/scrapercontroller.go:197\ngo.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1\n\tgo.opentelemetry.io/collector/receiver@v0.109.0/scraperhelper/scrapercontroller.go:173"
  },
  {
    "level": "error",
    "ts": 1747252160.16976,
    "caller": "scraperhelper/scrapercontroller.go:197",
    "msg": "Error scraping metrics",
    "kind": "receiver",
    "name": "hostmetrics",
    "data_type": "metrics",
    "error": "failed to read usage at /hostfs/conf: no such file or directory; failed to read usage at /hostfs/hostfs: no such file or directory; failed to read usage at /hostfs/hostfs/root: no such file or directory; failed to read usage at /hostfs/hostfs/var: no such file or directory; failed to read usage at /hostfs/hostfs/boot/efi: no such file or directory; failed to read usage at /hostfs/hostfs/boot/grub2/i386-pc: no such file or directory; failed to read usage at /hostfs/hostfs/.snapshots: no such file or directory; failed to read usage at /hostfs/hostfs/srv: no such file or directory; failed to read usage at /hostfs/hostfs/home: no such file or directory; failed to read usage at /hostfs/hostfs/boot/writable: no such file or directory; failed to read usage at /hostfs/hostfs/boot/grub2/x86_64-efi: no such file or directory; failed to read usage at /hostfs/hostfs/usr/local: no such file or directory; failed to read usage at /hostfs/hostfs/opt: no such file or directory",
    "scraper": "hostmetrics",
    "stacktrace": "go.opentelemetry.io/collector/receiver/scraperhelper.(*controller).scrapeMetricsAndReport\n\tgo.opentelemetry.io/collector/receiver@v0.109.0/scraperhelper/scrapercontroller.go:197\ngo.opentelemetry.io/collector/receiver/scraperhelper.(*controller).startScraping.func1\n\tgo.opentelemetry.io/collector/receiver@v0.109.0/scraperhelper/scrapercontroller.go:173"
  }
]
```

**Debug**

As I could not get into shell of otel-agent container, I tried manually mounting a pod to `/hostfs` similar as shows in daemonset to see it volume mounts correctly.

```shell
kubectl run hostfs-debug   --rm -it -n signoz   --image=busybox   --overrides='
{
  "spec": {
    "containers": [{
      "name": "shell",
      "image": "busybox",
      "command": ["sh"],
      "stdin": true,
      "tty": true,
      "volumeMounts": [{
        "name": "hostfs",
        "mountPath": "/hostfs",
        "readOnly": true
      }]
    }],
    "volumes": [{
      "name": "hostfs",
      "hostPath": { "path": "/" }
    }]
  }
}'
```

It shows the following:

```text
/hostfs # ls -lah
total 32K
drwxr-xr-x    1 root     root         232 Mar 22 02:49 .
drwxr-xr-x    1 root     root          46 May 14 20:47 ..
-rw-r--r--    1 root     root        1.6K Mar 22 02:48 .profile
drwx------    1 root     root          42 May 14 20:24 .snapshots
lrwxrwxrwx    1 root     root           7 Jan 28 09:26 bin -> usr/bin
dr-xr-xr-x    1 root     root         404 May 14 20:23 boot
-rw-r--r--    1 root     root          47 Mar 22 02:49 config.bootoptions
-rw-r--r--    1 root     root          71 Mar 22 02:48 config.partids
drwxr-xr-x   20 root     root        4.0K May 14 20:29 dev
drwxr-xr-x    1 root     root        1.4K May 14 20:28 etc
dr-xr-xr-x    1 root     root           0 Mar 22 02:47 home
drwxr-xr-x    1 root     root           0 Mar 22 02:49 image
lrwxrwxrwx    1 root     root           7 Jan 28 09:26 lib -> usr/lib
lrwxrwxrwx    1 root     root           9 Jan 28 09:26 lib64 -> usr/lib64
dr-xr-xr-x    1 root     root           0 Mar 22 02:47 mnt
dr-xr-xr-x    1 root     root           0 Mar 22 02:47 opt
dr-xr-xr-x  282 root     root           0 May 14 20:27 proc
drwx------    1 root     root         178 May 14 20:21 root
drwxr-xr-x   32 root     root         820 May 14 20:29 run
lrwxrwxrwx    1 root     root           8 Jan 28 09:26 sbin -> usr/sbin
dr-xr-xr-x    1 root     root           0 Mar 22 02:47 srv
dr-xr-xr-x   13 root     root           0 May 14 20:28 sys
drwxrwxrwt   11 root     root         220 May 14 20:47 tmp
drwxr-xr-x    1 root     root         124 May 14 20:24 usr
drwxr-xr-x    1 root     root          90 May 14 20:28 var
```

It is missing `/hostfs/conf` or `/hostfs/.snapshots`, but other than that most seems to be there, e.g. `/hostfs/boot`, `/hostfs/usr/local` (etc.). It is not under `/hostfs/hostfs` but `/hostfs`.

**Helm version**

`k8s-infra`: 0.12.3

**Additional information**

- Followed documentation section "Kubernetes nodes" at https://signoz.io/docs/userguide/hostmetrics/
- First time using Signoz

**Comment by Nageshbansal** [comment]
@ToshY Are you setting up any environment variables for `hostmetrics` scraper?

Also, could you please share your Helm values if possible?

**Comment by ToshY** [comment]
> [@ToshY](https://github.com/ToshY) Are you setting up any environment variables for `hostmetrics` scraper?
> 
> Also, could you please share your Helm values if possible?

<details><summary><code>k8s-infra values.yaml</code></summary>

```yaml
global:
  cloud: other
  clusterName: ${CLUSTER_NAME}
  deploymentEnvironment: ${CLUSTER_DEPLOYMENT_ENVIRONMENT}

otelCollectorEndpoint: ${HELM_K8S_INFRA_RELEASE_NAME}-otel-agent.${HELM_K8S_INFRA_NAMESPACE}.svc:4317
otelInsecure: true

otelAgent:
  enabled: true
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            max_recv_msg_size_mib: 8
presets:
  loggingExporter:
    enabled: false
  otlpExporter:
    enabled: true
  hostMetrics:
    enabled: true
    collectionInterval: 60s
    scrapers:
      cpu:
        metrics:
          system.cpu.logical.count:
            enabled: true
          system.cpu.physical.count:
            enabled: true
          system.cpu.utilization:
            enabled: true
      load: {}
      memory:
        metrics:
          system.memory.limit:
            enabled: true
          system.memory.utilization:
            enabled: true
      disk:
        exclude:
          devices:
            - ^ram\d+$
            - ^zram\d+$
            - ^loop\d+$
            - ^fd\d+$
            - ^hd[a-z]\d+$
            - ^sd[a-z]\d+$
            - ^vd[a-z]\d+$
            - ^xvd[a-z]\d+$
            - ^nvme\d+n\d+p\d+$
          match_type: regexp
      filesystem:
        exclude_fs_types:
          fs_types:
            - autofs
            - binfmt_misc
            - bpf
            - cgroup2?
            - configfs
            - debugfs
            - devpts
            - devtmpfs
            - fusectl
            - hugetlbfs
            - iso9660
            - mqueue
            - nsfs
            - overlay
            - proc
            - procfs
            - pstore
            - rpc_pipefs
            - securityfs
            - selinuxfs
            - squashfs
            - sysfs
            - tracefs
          match_type: strict
        exclude_mount_points:
          mount_points:
            - /dev/*
            - /proc/*
            - /sys/*
            - /run/credentials/*
            - /run/k3s/containerd/*
            - /var/lib/docker/*
            - /var/lib/containers/storage/*
            - /var/lib/kubelet/*
            - /snap/*
          match_type: regexp
      network:
        exclude:
          interfaces:
            - ^veth.*$
            - ^docker.*$
            - ^br-.*$
            - ^flannel.*$
            - ^cali.*$
            - ^cbr.*$
            - ^cni.*$
            - ^dummy.*$
            - ^tailscale.*$
            - ^lo$
          match_type: regexp
  kubeletMetrics:
    enabled: true
    collectionInterval: 30s
    authType: serviceAccount
    endpoint: ${env:K8S_HOST_IP}:10250
    insecureSkipVerify: true
    extraMetadataLabels:
      - container.id
      - k8s.volume.type
    metricGroups:
      - container
      - pod
      - node
      - volume
    metrics:
      k8s.node.cpu.usage:
        enabled: true
      k8s.node.uptime:
        enabled: true
      k8s.pod.cpu.usage:
        enabled: true
      k8s.pod.cpu_limit_utilization:
        enabled: true
      k8s.pod.cpu_request_utilization:
        enabled: true
      k8s.pod.memory_limit_utilization:
        enabled: true
      k8s.pod.memory_request_utilization:
        enabled: true
      k8s.pod.uptime:
        enabled: true
      container.cpu.usage:
        enabled: true
      k8s.container.cpu_limit_utilization:
        enabled: true
      k8s.container.cpu_request_utilization:
        enabled: true
      k8s.container.memory_limit_utilization:
        enabled: true
      k8s.container.memory_request_utilization:
        enabled: true
      container.uptime:
        enabled: true
  kubernetesAttributes:
    enabled: true
    # -- Whether to detect the IP address of agents and add it as an attribute to all telemetry resources.
    # If set to true, Agents will not make any k8s API calls, do any discovery of pods or extract any metadata.
    passthrough: false
    # -- Filters can be used to limit each OpenTelemetry agent to query pods based on specific
    # selector to only dramatically reducing resource requirements for very large clusters.
    filter:
      # -- Restrict each OpenTelemetry agent to query pods running on the same node
      node_from_env_var: K8S_NODE_NAME
    # -- Pod Association section allows to define rules for tagging spans, metrics,
    # and logs with Pod metadata.
    podAssociation:
      - sources:
        - from: resource_attribute
          name: k8s.pod.ip
      - sources:
        - from: resource_attribute
          name: k8s.pod.uid
      - sources:
        - from: connection
    # -- Which pod/namespace metadata to extract from a list of default metadata fields.
    extractMetadatas:
      - k8s.namespace.name
      - k8s.deployment.name
      - k8s.statefulset.name
      - k8s.daemonset.name
      - k8s.cronjob.name
      - k8s.job.name
      - k8s.node.name
      - k8s.node.uid
      - k8s.pod.name
      - k8s.pod.uid
      - k8s.pod.start_time
    # -- Which labels to extract from a list of metadata fields.
    extractLabels: []
    # -- Which annotations to extract from a list of metadata fields.
    extractAnnotations: []
  clusterMetrics:
    enabled: true
    collectionInterval: 30s
    resourceAttributes:
      k8s.pod.qos_class:
        enabled: true
      k8s.kubelet.version:
        enabled: true
      container.runtime:
        enabled: true
      container.runtime.version:
        enabled: true
      k8s.container.status.last_terminated_reason:
        enabled: true
    nodeConditionsToReport:
      - Ready
      - MemoryPressure
      - DiskPressure
      - PIDPressure
      - NetworkUnavailable
    allocatableTypesToReport:
      - cpu
      - memory
      # - ephemeral-storage
      # - storage
    metrics:
      k8s.node.condition:
        enabled: true
      k8s.pod.status_reason:
        enabled: true
  prometheus:
    enabled: false
  resourceDetection:
    enabled: true
    timeout: 2s
    override: false
  k8sEvents:
    enabled: true
```

</details> 

<details><summary><code>signoz values.yaml</code></summary>

```yaml
global:
  storageClass: "longhorn"
  clusterName: ${CLUSTER_NAME}

clickhouse:
  enabled: true
  installCustomStorageClass: true
  zookeeper:
    enabled: true
    podAnnotations:
      signoz.io/scrape: "true"
      signoz.io/port: "9141"
      signoz.io/path: "/metrics"
  user: ${CLICKHOUSE_USER}
  password: ${CLICKHOUSE_PASSWORD}
  layout:
    shardsCount: 1
    replicasCount: 1
  coldStorage:
    enabled: true
    # Set free space size on default disk in bytes
    defaultKeepFreeSpaceBytes: "10485760" # 10MiB
    type: s3
    endpoint: ${CLICKHOUSE_COLDSTORAGE_S3_ENDPOINT}
    accessKey: ${CLICKHOUSE_COLDSTORAGE_S3_ACCESS_KEY}
    secretAccess: ${CLICKHOUSE_COLDSTORAGE_S3_SECRET_ACCESS}
  persistence:
    enabled: true
    size: 15Gi

signoz:
  name: "signoz"
  replicaCount: 1
  configVars:
    storage: clickhouse
    goDebug: netdns=go
    telemetryEnabled: true
    deploymentType: kubernetes-helm
  persistence:
    enabled: true
    size: 1Gi

# Default values for schemaMigrator
schemaMigrator:
  enabled: true
  name: "schema-migrator"
  args:
    - "--up="

otelCollector:
  name: "otel-collector"
  ports:
    otlp:
      # -- Whether to enable service port for OTLP gRPC
      enabled: true
      # -- Container port for OTLP gRPC
      containerPort: 4317
      # -- Service port for OTLP gRPC
      servicePort: 4317
      # -- Node port for OTLP gRPC
      nodePort: ""
      # -- Protocol to use for OTLP gRPC
      protocol: TCP
    otlp-http:
      # -- Whether to enable service port for OTLP HTTP
      enabled: true
      # -- Container port for OTLP HTTP
      containerPort: 4318
      # -- Service port for OTLP HTTP
      servicePort: 4318
      # -- Node port for OTLP HTTP
      nodePort: ""
      # -- Protocol to use for OTLP HTTP
      protocol: TCP
    jaeger-compact:
      # -- Whether to enable service port for Jaeger Compact
      enabled: false
      # -- Container port for Jaeger Compact
      containerPort: 6831
      # -- Service port for Jaeger Compact
      servicePort: 6831
      # -- Node port for Jaeger Compact
      nodePort: ""
      # -- Protocol to use for Jaeger Compact
      protocol: UDP
    jaeger-thrift:
      # -- Whether to enable service port for Jaeger Thrift HTTP
      enabled: true
      # -- Container port for Jaeger Thrift
      containerPort: 14268
      # -- Service port for Jaeger Thrift
      servicePort: 14268
      # -- Node port for Jaeger Thrift
      nodePort: ""
      # -- Protocol to use for Jaeger Thrift
      protocol: TCP
    jaeger-grpc:
      # -- Whether to enable service port for Jaeger gRPC
      enabled: true
      # -- Container port for Jaeger gRPC
      containerPort: 14250
      # -- Service port for Jaeger gRPC
      servicePort: 14250
      # -- Node port for Jaeger gRPC
      nodePort: ""
      # -- Protocol to use for Jaeger gRPC
      protocol: TCP
    zipkin:
      # -- Whether to enable service port for Zipkin
      enabled: false
      # -- Container port for Zipkin
      containerPort: 9411
      # -- Service port for Zipkin
      servicePort: 9411
      # -- Node port for Zipkin
      nodePort: ""
      # -- Protocol to use for Zipkin
      protocol: TCP
    metrics:
      # -- Whether to enable service port for internal metrics
      enabled: true
      # -- Container port for internal metrics
      containerPort: 8888
      # -- Service port for internal metrics
      servicePort: 8888
      # -- Node port for internal metrics
      nodePort: ""
      # -- Protocol to use for internal metrics
      protocol: TCP
    zpages:
      # -- Whether to enable service port for ZPages
      enabled: false
      # -- Container port for Zpages
      containerPort: 55679
      # -- Service port for Zpages
      servicePort: 55679
      # -- Node port for Zpages
      nodePort: ""
      # -- Protocol to use for Zpages
      protocol: TCP
    pprof:
      # -- Whether to enable service port for pprof
      enabled: false
      # -- Container port for pprof
      containerPort: 1777
      # -- Service port for pprof
      servicePort: 1777
      # -- Node port for pprof
      nodePort: ""
      # -- Protocol to use for pprof
      protocol: TCP
    logsheroku:
      # -- Whether to enable service port for logsheroku
      enabled: true
      # -- Container port for logsheroku
      containerPort: 8081
      # -- Service port for logsheroku
      servicePort: 8081
      # -- Node port for logsheroku
      nodePort: ""
      # -- Protocol to use for logsheroku
      protocol: TCP
    logsjson:
      # -- Whether to enable service port for logsjson
      enabled: true
      # -- Container port for logsjson
      containerPort: 8082
      # -- Service port for logsjson
      servicePort: 8082
      # -- Node port for logsjson
      nodePort: ""
      # -- Protocol to use for logsjson
      protocol: TCP
    keda:
      enabled: false

signoz-otel-gateway:
  enabled: false
```

</details>

**Comment by Nageshbansal** [comment]
Hey @ToshYx, I've tested the `k8s-infra` Helm values you shared, but I'm not able to reproduce the issue you're facing. 

Would you be open to a quick call so we can troubleshoot it together? I'd appreciate it if you could show me the issue from your end.

**Comment by ToshY** [comment]
> Hey [@toshyx](https://github.com/toshyx), I've tested the `k8s-infra` Helm values you shared, but I'm not able to reproduce the issue you're facing.
> 
> Would you be open to a quick call so we can troubleshoot it together? I'd appreciate it if you could show me the issue from your end.

When I manually change the `k8s-infra-otel-agent` config map and set the `root_path` from `/hostfs` to `/`, I no longer get the error.

```yaml
data:
  otel-agent-config.yaml: |-
    receivers:
      hostmetrics:
        collection_interval: 60s
        root_path: /
```

I now however get `Exporting failed` error. I do not know if this is related to the `hostmetrics`.

```text
{"level":"info","ts":1754433895.3829975,"caller":"exporterhelper/retry_sender.go:118","msg":"Exporting failed. Will retry the request after interval.","kind":"exporter","data_type":"logs","name":"otlp","error":"rpc error: code = DeadlineExceeded desc = received context error while waiting for new LB policy update: context deadline exceeded","interval":"2.776447905s"}
{"level":"info","ts":1754433897.989734,"caller":"exporterhelper/retry_sender.go:118","msg":"Exporting failed. Will retry the request after interval.","kind":"exporter","data_type":"logs","name":"otlp","error":"rpc error: code = DeadlineExceeded desc = received context error while waiting for new LB policy update: context deadline exceeded","interval":"2.50743588s"}
{"level":"info","ts":1754433898.993563,"caller":"exporterhelper/retry_sender.go:118","msg":"Exporting failed. Will retry the request after interval.","kind":"exporter","data_type":"logs","name":"otlp","error":"rpc error: code = DeadlineExceeded desc = received context error while waiting for new LB policy update: context deadline exceeded","interval":"3.97703858s"}
{"level":"info","ts":1754433899.3621485,"caller":"exporterhelper/retry_sender.go:118","msg":"Exporting failed. Will retry the request after interval.","kind":"exporter","data_type":"logs","name":"otlp","error":"rpc error: code = DeadlineExceeded desc = received context error while waiting for new LB policy update: context deadline exceeded","interval":"9.309008865s"}
```

**Comment by ToshY** [comment]
@Nageshbansal I think we can close this for now. I have been able to succesfully deploy it. I am not quite sure why I had trouble with the `rootPath` of `hostMetrics` initially, but I removed that now and I no longer have the initial issue (and the last issue I mentioned).

I've deployed `k8s-infra` first, and then `signoz` with these values and it seems to work for me as the pods are now healthy and running.

<details><summary><code>k8s-infra/values.yaml</code></summary>

```yaml
global:
  cloud: other
  clusterName: ${CLUSTER_NAME}
  deploymentEnvironment: ${CLUSTER_DEPLOYMENT_ENVIRONMENT}

otelCollectorEndpoint: ${HELM_K8S_INFRA_RELEASE_NAME}-otel-agent.${HELM_K8S_INFRA_NAMESPACE}.svc:4317
otelInsecure: true

otelAgent:
  enabled: true
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            max_recv_msg_size_mib: 8
presets:
  logsCollection:
    enabled: true
  otlpExporter:
    enabled: true
  hostMetrics:
    enabled: true
    collectionInterval: 60s
    cpu:
      metrics:
        system.cpu.logical.count:
          enabled: true
        system.cpu.physical.count:
          enabled: true
        system.cpu.utilization:
          enabled: true
    load: {}
    memory:
      metrics:
        system.memory.limit:
          enabled: true
        system.memory.utilization:
          enabled: true
  kubeletMetrics:
    enabled: true
    collectionInterval: 30s
    endpoint: ${env:K8S_HOST_IP}:10250
  kubernetesAttributes:
    enabled: true
  prometheus:
    enabled: false
  resourceDetection:
    enabled: true
  k8sEvents:
    enabled: true
```

</details> 

<details><summary><code>signoz/values.yaml</code></summary>

```yaml
global:
  storageClass: "longhorn"
  clusterName: ${CLUSTER_NAME}

clickhouse:
  enabled: true
  installCustomStorageClass: true
  zookeeper:
    enabled: true
  user: ${CLICKHOUSE_USER}
  password: ${CLICKHOUSE_PASSWORD}
  layout:
    shardsCount: 1
    replicasCount: 1
  coldStorage:
    enabled: true
    defaultKeepFreeSpaceBytes: "10485760" # 10MiB
    type: s3
    endpoint: ${CLICKHOUSE_COLDSTORAGE_S3_ENDPOINT}
    accessKey: ${CLICKHOUSE_COLDSTORAGE_S3_ACCESS_KEY}
    secretAccess: ${CLICKHOUSE_COLDSTORAGE_S3_SECRET_ACCESS}
  persistence:
    enabled: true
    size: 15Gi

signoz:
  name: "signoz"
  replicaCount: 1
  env:
    signoz_jwt_secret: ${SIGNOZ_JWT_SECRET}
    signoz_telemetrystore_provider: clickhouse
    signoz_analytics_enabled: false
    dot_metrics_enabled: true
  persistence:
    enabled: true
    size: 1Gi

# Default values for schemaMigrator
schemaMigrator:
  enabled: true

otelCollector:
  name: "otel-collector"
  ports:
    otlp:
      enabled: true
    otlp-http:
      enabled: true
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: true
    jaeger-grpc:
      enabled: true
    zipkin:
      enabled: false
    metrics:
      enabled: true
    zpages:
      enabled: false
    pprof:
      enabled: false
    logsheroku:
      enabled: true
    logsjson:
      enabled: true
    keda:
      enabled: false

signoz-otel-gateway:
  enabled: false
```

</details> 

---

Now just have to figure out how the dashboards work and how to collect logs and display host metrics 🙂 

Thank you for your help!
