### ISSUE TITLE
Clickhouse storage configuration prefers global value

### ISSUE THREAD

**Issue by npalladium** [SigNoz/charts#671]
Given the following values:
```yaml
global:
  storageClass: global-value
clickhouse:
  enabled: true
  persistence:
    storageClass: other-value
```

The Clickhouse Installation will use `global-value` as the storage class instead of `other-value`.

This is because the [code](https://github.com/SigNoz/charts/blob/63d89df43a393637d7d2c82635b6dba1c583ac81/charts/clickhouse/templates/clickhouse-instance/clickhouse-instance.yaml#L385) has `{{- $storageClass := default .Values.persistence.storageClass .Values.global.storageClass -}}`. The [default](https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-default-function) function is to be used like `default DEFAULT_VALUE GIVEN_VALUE` (which is kinda unlike every other language, but makes sense as it is designed to be used with `|`).

If the global value being preferred is the intended behaviour, it should be pointed out clearly because that is unexpected.
