### ISSUE TITLE
PV reconciliation error causes PV to be outOfSync (requires pruning) on argocd

### ISSUE THREAD

**Issue by bautistamad** [SigNoz/charts#86]
Hello SigNoZ team.

I am trying to deploy SigNoZ with ArgoCD and I have the following problem:

![pv](https://user-images.githubusercontent.com/75149705/194335604-df035222-e13f-4075-b436-9a8691187adf.png)
ArgoCD is trying to delete a PV that they should not manage and is in a constant loop.

![crd](https://user-images.githubusercontent.com/75149705/194336868-ca4117ac-4970-4be9-a3db-8aedc836b8a2.png)
CRD immediatly OutOfSync

ArgoCD chart version: 5.5.8 

I found  the following related issues:
https://github.com/Altinity/clickhouse-operator/issues/958
https://github.com/argoproj/argo-cd/issues/3391

**Comment by bautistamad** [comment]
any update of this?

**Comment by AurimasNav** [comment]
> any update of this?

I was able to solve/workaround it as per the issue you mentioned - https://github.com/Altinity/clickhouse-operator/issues/958
by creating a `ClickHouseOperatorConfiguration` resource:

```yaml
apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseOperatorConfiguration
metadata:
  name: signoz-clickhouse-argocd-pv-nomanage
  namespace: signoz
spec:
  excludeFromPropagationLabels: ["app.kubernetes.io/instance", "argocd.argoproj.io/instance"]
  label:
    exclude: ["app.kubernetes.io/instance", "argocd.argoproj.io/instance"]
```

Could it possibly be added to signoz chart as configuration parameter in values.yaml?
