### ISSUE TITLE
Cannot install signoz with Flux helm-controller

### ISSUE THREAD

**Issue by petrmac** [SigNoz/charts#94]
Flux is reporting error with helm chart. Looks like the template is malformed.

```
Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 23: mapping key "nodePort" already defined at line 20
```

corresponding helm release:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: signoz
  namespace: signoz
spec:
  releaseName: signoz
  chart:
    spec:
      chart: signoz
      version: "0.4.2"
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 30
```

**Comment by petrmac** [comment]
Does not help. When running `helm template test .` in the cloned repo, it shows a bunch nodePort values ` nodePort: ` and more of ` nodePort: null` this is probably not correct. Not sure which is right yet.

**Comment by petrmac** [comment]
Since these with empty value are the last ones, they are probably not correct. Will try earlier version of the chart.

**Comment by petrmac** [comment]
Hmm, this looks weird: 
```
# Source: signoz/templates/otel-collector-metrics/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-signoz-otel-collector-metrics
  labels:
    helm.sh/chart: signoz-0.4.3
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: test
    app.kubernetes.io/component: otel-collector-metrics
    app.kubernetes.io/version: "0.11.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:    
    - name: health-check
      port: 13133
      nodePort: null
      targetPort: health-check
      protocol: TCP
      nodePort: 
  selector:
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: test
    app.kubernetes.io/component: otel-collector-metrics
```

or this:
```
# Source: signoz/templates/otel-collector/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-signoz-otel-collector
  labels:
    helm.sh/chart: signoz-0.4.3
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: test
    app.kubernetes.io/component: otel-collector
    app.kubernetes.io/version: "0.11.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:    
    - name: jaeger-grpc
      port: 14250
      nodePort: null
      targetPort: jaeger-grpc
      protocol: TCP
      nodePort: 
    - name: jaeger-thrift
      port: 14268
      nodePort: null
      targetPort: jaeger-thrift
      protocol: TCP
      nodePort: 
    - name: metrics
      port: 8888
      nodePort: null
      targetPort: metrics
      protocol: TCP
      nodePort: 
    - name: otlp
      port: 4317
      nodePort: null
      targetPort: otlp
      protocol: TCP
      nodePort: 
    - name: otlp-http
      port: 4318
      nodePort: null
      targetPort: otlp-http
      protocol: TCP
      nodePort: 
  selector:
    app.kubernetes.io/name: signoz
    app.kubernetes.io/instance: test
    app.kubernetes.io/component: otel-collector
```

node port defined multiple times in the map.
